### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by madvas** [district0x/district-ui-notification#1]
1. `::events/stop` should unregister `:forward-events`
2. `::init` event is not used/documented, can be removed
3. There should probably be some property to define delay between shows, so hide animation has some time. Sth like `:default-delay-between-notifications`
4. Unnecessary `s/valid?` in notification.cljs
5. I think wait-for should be indented just with 2 spaces, since it's often deeply nested: 
```clojure
(wait-for [::events/show-notification]
  (is (= "foo" (:message @notification)))
  (is (= "bar" (:action-href @notification)))
  (wait-for [::events/clear-queue]))
```
6. In readme "Include `[district.ui.notification]`" should go on second line. You force second line with 2 spaces at the end of previous line. 

Otherwise nice module, good job!

**Comment by fbielejec** [comment]
Ad 5) I think the formatter adheres to the style-guide, which mentions that macro/functions arguments spanning multiple lines shoud get vertically aligned, as in:
```clojure
(filter even?
        (range 1 10))
```
versus:
```clojure
(filter even?
  (range 1 10))
```  
The same guide says to use 2 spaces to indent the bodies of forms that have body parameters, like:
```clojure
(when x
  (do-y))
```
We can agree among ourselves to use the *form* indentation for this macro. I'll start keeping a list of rules for emacs init file for a future re-use.

**Comment by madvas** [comment]
Well I this `wait-for` is more like `when` rather than `filter`. Since it has body that gets executed under some condition and exactly 1 parameter. Which is the same definition as `when`
